#!/usr/bin/python

import os
import sys
import getpass
from sys import argv
from pareload.extras import extras

passfile = open(extras.passpath)


HELP_MESSAGE = '''

USAGE: set password for parelaod

pa-pass [-p]

--help                     -h               Display the help message and exit
--set-password=[password]  -p [password]    Sets the password. If a password is not given. It asks user for password.

'''
def main():
    if len(argv) == 1:
        key = passfile.read()
        if key == "":
            print "You haven't set a password yet. use th -p argument to set a password"
        else:
            print key
    else:
        if argv[1] == '-p':
            #set password
            if len(argv) < 3: ##if password is not specified, get it from stdin
                password = getpass.getpass('Password: ') # get password from stdin
            else:
                password = argv[2]
        elif argv[1][:10] == "--password":
            if argv[11] == '=':
                password = argv[1][11:]
            else:
                password = getpass.getpass('password: ')    #get password from stdin

        fw = open(extras.passpath, 'w')
        fw.write(password) # encode pass and save in in passkey file
        fw.close()

if __name__ == '__main__':
    main()

sys.exit(0)
